export default function Head() {
  return (
    <>
      <title>About 💁‍♂️</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta
        name="About page description goes here"
        content="Generated by create next app"
      />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
